export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

/*

app/layout.jsx

Es basicamente un componente
Es el contendor raiz de toda la aplicacion. 
Este layout contiene un <html> y un <body> y lo que cambia seria el contenido del <body>, es decir al ser el RootLayout un componente este recibe props: {children} (o tambien llamados elementos hijos) los cuales se renderizaran dentro del body.
Recordar que el {children} es lo dinamico, lo que ira cambiando dependiendo las rutas que visitemos
Cualquier ruta que yo visite, tendrá esta estructura(layout) como principal
Podemos añadir un navbar, de manera que este se quede estatico mientras nos movemos por todas las rutas que hemos creado

*/
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav>
          <h1>Navbar</h1>
          <ul>
            <li>Home</li>
            <li>About</li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
